# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MultimodeQt.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 500)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.btSource = QtGui.QPushButton(self.centralwidget)
        self.btSource.setGeometry(QtCore.QRect(20, 120, 121, 32))
        self.btSource.setObjectName(_fromUtf8("btSource"))
        self.step1 = QtGui.QLabel(self.centralwidget)
        self.step1.setGeometry(QtCore.QRect(20, 79, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Myriad Pro"))
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.step1.setFont(font)
        self.step1.setObjectName(_fromUtf8("step1"))
        self.step3 = QtGui.QLabel(self.centralwidget)
        self.step3.setGeometry(QtCore.QRect(230, 80, 170, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Myriad Pro"))
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.step3.setFont(font)
        self.step3.setObjectName(_fromUtf8("step3"))
        self.btSave = QtGui.QPushButton(self.centralwidget)
        self.btSave.setGeometry(QtCore.QRect(250, 120, 161, 32))
        self.btSave.setObjectName(_fromUtf8("btSave"))
        self.step2 = QtGui.QLabel(self.centralwidget)
        self.step2.setGeometry(QtCore.QRect(20, 170, 261, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Myriad Pro"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.step2.setFont(font)
        self.step2.setObjectName(_fromUtf8("step2"))
        self.hArrivee = QtGui.QTimeEdit(self.centralwidget)
        self.hArrivee.setGeometry(QtCore.QRect(280, 250, 71, 22))
        self.hArrivee.setTime(QtCore.QTime(9, 0, 0))
        self.hArrivee.setObjectName(_fromUtf8("hArrivee"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(280, 230, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.DistMax = QtGui.QSpinBox(self.centralwidget)
        self.DistMax.setGeometry(QtCore.QRect(280, 300, 51, 22))
        self.DistMax.setMaximum(99999999)
        self.DistMax.setProperty("value", 15)
        self.DistMax.setObjectName(_fromUtf8("DistMax"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(280, 280, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(340, 300, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 391, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Titre = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Myriad Pro"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Titre.setFont(font)
        self.Titre.setObjectName(_fromUtf8("Titre"))
        self.verticalLayout.addWidget(self.Titre)
        self.soustitre = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Myriad Pro"))
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.soustitre.setFont(font)
        self.soustitre.setObjectName(_fromUtf8("soustitre"))
        self.verticalLayout.addWidget(self.soustitre)
        self.console = QtGui.QTextEdit(self.centralwidget)
        self.console.setGeometry(QtCore.QRect(420, 10, 371, 421))
        self.console.setObjectName(_fromUtf8("console"))
        self.btSource_2 = QtGui.QPushButton(self.centralwidget)
        self.btSource_2.setGeometry(QtCore.QRect(80, 390, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btSource_2.setFont(font)
        self.btSource_2.setObjectName(_fromUtf8("btSource_2"))
        self.calendar = QtGui.QCalendarWidget(self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(20, 230, 240, 141))
        self.calendar.setObjectName(_fromUtf8("calendar"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 210, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 440, 781, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.btkey = QtGui.QPushButton(self.centralwidget)
        self.btkey.setGeometry(QtCore.QRect(310, 10, 101, 31))
        self.btkey.setObjectName(_fromUtf8("btkey"))
        self.layoutWidget.raise_()
        self.btSource.raise_()
        self.step1.raise_()
        self.step3.raise_()
        self.btSave.raise_()
        self.step2.raise_()
        self.hArrivee.raise_()
        self.label_11.raise_()
        self.DistMax.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.console.raise_()
        self.btSource_2.raise_()
        self.calendar.raise_()
        self.label_14.raise_()
        self.progressBar.raise_()
        self.btkey.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.btSource.setText(_translate("MainWindow", "Fichier OD ...", None))
        self.step1.setText(_translate("MainWindow", "1. Selectionez un fichier OD :", None))
        self.step3.setText(_translate("MainWindow", "2. Enregistrez les résultats", None))
        self.btSave.setText(_translate("MainWindow", "Enregistrez vos résutats...", None))
        self.step2.setText(_translate("MainWindow", "3. Paramétrez votre recherche :", None))
        self.label_11.setText(_translate("MainWindow", "Heure d\'arrivée", None))
        self.label_12.setText(_translate("MainWindow", "Tp marche max", None))
        self.label_13.setText(_translate("MainWindow", "Minutes :", None))
        self.Titre.setText(_translate("MainWindow", "IDD Multimode", None))
        self.soustitre.setText(_translate("MainWindow", "Comparateur multimodal de temps de trajets", None))
        self.btSource_2.setText(_translate("MainWindow", "Rechercher", None))
        self.label_14.setText(_translate("MainWindow", "Date d\'arrivée", None))
        self.btkey.setText(_translate("MainWindow", "Clés d\'API", None))

